site_name: Raaj's Engineering & CS Portfolio
nav:
- Home: index.md
- Courses & Projects: 
  - AP Networking (2025-2026):
    - Overview: courses/ap_networking/index.md
    - Component Cards & Software Slips: courses/ap_networking/component-cards-and-software-slips.md
    - Command Line Interface: courses/ap_networking/cli.md
    - Network Troubleshooting: courses/ap_networking/troubleshooting.md
    - Determining Security Controls for Devices: courses/ap_networking/security-controls.md
    - Implementing Security for Devices: courses/ap_networking/device-security.md
    - Networking and Data Movement: courses/ap_networking/networking_data_movement.md
    - Network Foundations: courses/ap_networking/network_foundations.md
    - Why Can't These Two Computers Talk to Each Other?: courses/ap_networking/why_cant_these_two_computers_talk.md
    - Physical Addressing and Logical Addressing: courses/ap_networking/physical_logical_addressing.md
  - Honors Senior Engineering (2025-2026): 
    - Overview: courses/senior_engineering/index.md
    - Capstone Project: courses/senior_engineering/capstone.md
    - Daily Log: courses/senior_engineering/daily_log.md
    - Owl: courses/senior_engineering/owl.md
    - Pen: courses/senior_engineering/pen.md
    - PCB Milling: courses/senior_engineering/pcb_milling.md
    - Topography: courses/senior_engineering/topography.md
  - Honors Data Analytics (2025): 
    - Overview: courses/data_analytics/index.md
    - Excel: courses/data_analytics/excel.md
    - Python: courses/data_analytics/python.md
    - Data Cleaning: courses/data_analytics/data_cleaning.md
    - Bootstrapping: courses/data_analytics/bootstrapping.md
    - ANOVA: courses/data_analytics/anova.md
    - Machine Learning: courses/data_analytics/machine_learning.md
  - Civil Engineering (2024): 
    - Overview: courses/civil_engineering/index.md
    - Bridge Building and Testing: courses/civil_engineering/bridge_building_and_testing.md
    - Windmill Design and Optimization: courses/civil_engineering/windmill_optimization.md
    - Water Turbidity Testing: courses/civil_engineering/water_turbidity.md
  - Engineering I (2022):
    - Overview: courses/engineering_1/index.md
    - Thinking Out of the Box: courses/engineering_1/box.md
    - Easily Suede: courses/engineering_1/keychain.md
    - Plane and Simple: courses/engineering_1/3d_printing.md
    - The Ohm Depot: courses/engineering_1/ohm_depot.md
    - A Cold Solder: courses/engineering_1/cold_solder.md
    - Grab a Byte: courses/engineering_1/grab_a_byte.md
    - Final Project: courses/engineering_1/final_project.md
  - Engineering II (2023): 
    - Overview: courses/engineering_2/index.md
    - Deep Dive into Fusion 360: courses/engineering_2/fusion360.md
    - Milling About: courses/engineering_2/milling_about.md
    - Pressing Charges: courses/engineering_2/pressing_charges.md
    - Board to be Wild: courses/engineering_2/cutting_board.md
    - Final Project: courses/engineering_2/final_project.md
- About: about.md
theme:
  name: dracula
  logo: media/headshot.png
  favicon: media/headshot.png
extra:
  social:
    - image: media/headshot.png
extra_javascript:
  - js/collapse-headers.js
extra_css:
  - stylesheets/extra.css
  - stylesheets/sidebar-collapse-diamond-fix.css
  - stylesheets/collapse-headers.css
markdown_extensions:
  - attr_list
  - pymdownx.superfences